services:
    postgres:
        hostname: postgres
        image: postgres
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_USER: app
            POSTGRES_DB: mailixer
        volumes:
            - type: volume
              source: db-data
              target: /var/lib/postgresql/data
              volume:
                  nocopy: true
        networks:
            - mailixer-net
    app:
        depends_on:
            -   ui
            -   postgres
        hostname: app
        build:
            context: .
        restart: always
        entrypoint: ["php", "artisan", "serve", "--host=app"]
        ports:
            - 80:8000
        volumes:
            -   type: bind
                source: .
                target: /app
        networks:
            - mailixer-net
    ui:
        hostname: ui
        image: node:14.21.3-bullseye
        restart: always
        working_dir: /app
        command: [ "npm", "run", "dev" ]
        ports:
            - 5173:5173
        volumes:
            -   type: bind
                source: .
                target: /app

    queue-worker:
        build:
            context: .
        restart: always
        working_dir: /app
        entrypoint: [ "php", "artisan", "queue:listen" ]
        volumes:
            -   type: bind
                source: ./
                target: /app
        networks:
            - mailixer-net

networks:
    mailixer-net:

volumes:
    db-data:

