services:
  postgres:
    hostname: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: app
      POSTGRES_DB: mailixer
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    networks:
      - mailixer-net
  app:
    depends_on:
      - ui
      - postgres
    hostname: app
    build:
      context: .
    restart: always
    entrypoint: ['php', 'artisan', 'serve', '--host=app']
    ports:
      - 80:8000
    volumes:
      - type: bind
        source: .
        target: /app
    networks:
      - mailixer-net
  ui:
    hostname: ui
    image: node:14.21.3-bullseye
    restart: always
    working_dir: /app
    command: ['npm', 'run', 'dev']
    ports:
      - 5173:5173
    volumes:
      - type: bind
        source: .
        target: /app

  send-queue-worker:
    depends_on:
      - rabbitmq
    build:
      context: .
    restart: always
    working_dir: /app
    entrypoint: ['php', 'artisan', 'queue:listen']
    volumes:
      - type: bind
        source: ./
        target: /app
    networks:
      - mailixer-net

  feedback-queue-worker:
    build:
      context: .
    restart: always
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    networks:
      - mailixer-net
    entrypoint:
      [
        'php',
        'artisan',
        'queue:work',
        '--queue=mailixer-feedback-queue',
        'rabbitmq',
      ]

  haraka:
    hostname: haraka
    image: instrumentisto/haraka:latest
    restart: no
    volumes:
      - type: bind
        source: ./smtp/haraka
        target: /etc/haraka
    networks:
      - mailixer-net
    ports:
      - 8081:587

  rabbitmq:
    hostname: rabbitmq # RabbitMQ node name is same as hostname
    image: rabbitmq:3-management
    environment: # Make sure to delete rabbitmq-data volume everytime these two env variable change
      RABBITMQ_DEFAULT_USER: foo
      RABBITMQ_DEFAULT_PASS: example
    volumes:
      - type: volume
        source: rabbitmq-data
        target: /var/lib/rabbitmq # RabbitMQ database directory
        volume:
          nocopy: true
    ports:
      - 8080:15672
    networks:
      - mailixer-net

networks:
  mailixer-net:

volumes:
  db-data:
  rabbitmq-data:
