/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    'sanctum.csrf-cookie': []
    'log-viewer.hosts': []
    'log-viewer.folders': []
    'log-viewer.folders.request-download': [
      {
        name: 'folderIdentifier'
      },
    ]
    'log-viewer.folders.clear-cache': [
      {
        name: 'folderIdentifier'
      },
    ]
    'log-viewer.folders.delete': [
      {
        name: 'folderIdentifier'
      },
    ]
    'log-viewer.files': []
    'log-viewer.files.request-download': [
      {
        name: 'fileIdentifier'
      },
    ]
    'log-viewer.files.clear-cache': [
      {
        name: 'fileIdentifier'
      },
    ]
    'log-viewer.files.delete': [
      {
        name: 'fileIdentifier'
      },
    ]
    'log-viewer.files.clear-cache-all': []
    'log-viewer.files.delete-multiple-files': []
    'log-viewer.logs': []
    'log-viewer.folders.download': [
      {
        name: 'folderIdentifier'
      },
    ]
    'log-viewer.files.download': [
      {
        name: 'fileIdentifier'
      },
    ]
    'log-viewer.index': [
      {
        name: 'view'
      },
    ]
    'ignition.healthCheck': []
    'ignition.executeSolution': []
    'ignition.updateConfig': []
    home: []
    login: []
    logout: []
    'subscribe.index': [
      {
        name: 'token'
      },
    ]
    'subscribe.success': [
      {
        name: 'token'
      },
    ]
    unsubscribe: [
      {
        name: 'unsubscribeToken'
      },
    ]
    'unsubscribe.oneClick': [
      {
        name: 'unsubscribeToken'
      },
    ]
    'dashboard.index': []
    'dashboard.customization': []
    'dashboard.subscribers': []
    'dashboard.composeNewsletter': []
    'dashboard.draftNewsletter': []
    'dashboard.batch.unsubscribe': []
    'dashboard.batch.blacklist': []
    'dashboard.subscription.records': [
      {
        name: 'from'
      },
      {
        name: 'to'
      },
    ]
    'setting.account': []
    'user.profile': [
      {
        name: 'userId'
      },
    ]
    'register.page': []
    'verification.verify': [
      {
        name: 'id'
      },
      {
        name: 'hash'
      },
    ]
  }
}
export {}
