import {
    ArrowUpSquare,
    Bold,
    BookOpen,
    ChevronDown,
    ChevronsUpDown,
    Clipboard,
    Columns,
    FolderOpen,
    GripVertical,
    Heading1,
    Heading2,
    Heading3,
    Image,
    Italic,
    Layout,
    Link,
    List,
    Loader2,
    LogOut,
    MoreHorizontal,
    Newspaper,
    PenSquare,
    Send,
    Settings,
    Strikethrough,
    Trash,
    Underline,
    Undo2,
    UserCheck,
    UserMinus,
    Users2,
    UserX,
    X,
    XCircle,
    Mail,
    Lock,
    Clock4,
    CircleEllipsis,
    ChevronRight,
    BarChartBig,
    Calendar
} from "lucide-react";

const Icons = {
    XCircle: XCircle,
    ArrowUpSquare: ArrowUpSquare,
    Settings: Settings,
    LogOut: LogOut,
    BookOpen: BookOpen,
    Layout: Layout,
    UserCheck: UserCheck,
    Clipboard: Clipboard,
    Cross2Icon: X,
    List: List,
    UserMinus: UserMinus,
    Newspaper: Newspaper,
    Undo2: Undo2,
    TwoUsers: Users2,
    PenSquare: PenSquare,
    FolderOpen: FolderOpen,
    Trash: Trash,
    Bold: Bold,
    Italic: Italic,
    Underline: Underline,
    Strikethrough: Strikethrough,
    Send: Send,
    GripVertical: GripVertical,
    ChevronDown,
    Image: Image,
    Heading1: Heading1,
    Heading2: Heading2,
    Heading3: Heading3,
    UserX: UserX,
    Loader2: Loader2,
    Link: Link,
    ChevronsUpDown: ChevronsUpDown,
    MoreHorizontal: MoreHorizontal,
    Columns: Columns,
    Mail: Mail,
    Lock: Lock,
    Clock4: Clock4,
    CircleEllipsis: CircleEllipsis,
    ChevronRight: ChevronRight,
    BarChartBig: BarChartBig,
    Calendar: Calendar
};

export {Icons};
